### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-mlhmenu#2]
Update README with example usage.

**Comment by beroes** [comment]
What examples do you mean @ain, should I put some example HTML markup, or should I point to example usage somewhere in the internet?

**Comment by ain** [comment]
Perfect, that's exactly what I meant! Feel free to adjust though as you go through with it :)

Resolving the ticket complete as of ddb4fc2c54bc62eab4f0baad3485fbdbe5c7c43e
