### ISSUE TITLE
Add dependency mmenu

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-mlhmenu#7]
https://github.com/BeSite/jQuery.mmenu

**Comment by ain** [comment]
@GeorgMeyer23 AFAIK, mmenu is only required on mobile which makes this module fully functional without the mmenu as a dependency. @beroes please confirm and change to `enhancement` if appropriate.

I'd suggest explicitly documenting this in README.

**Comment by beroes** [comment]
Mmenu is not required for the navigation to work even on mobile.
